env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/sa/sa"
    rclone_config: "ENCRYPTED[e6b57489e5e364b7013542660ce6823fc390190fed3d96d36c5df048fb2750a23cb0d4180171363a566d38eb8ce8bf2f]"

task:
    name: test
    timeout_in: 120m
    container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
    show_script:
    - cat $CIRRUS_WORKING_DIR/build_rom.sh
