env:
    CIRRUS_CLONE_DEPTH: 1
    BUILD_HOSTNAME: "cirrus-ci.org"
    
task:
  name: "Compile Rom"
  timeout_in: 4h
  container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
      stateful: true
      greedy: true
      volumes:
          - /home/cirrus/roms:/home/cirrus/roms
          - /home/cirrus/ccache:/home/cirrus/ccache
          - /home/cirrus/.config:/home/cirrus/.config

  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - repo init -u https://github.com/Sa-Sajjad/android_manifest_nusa -b 10
      - repo sync -c --force-sync --no-tags --no-clone-bundle
      - git clone https://github.com/Sa-Sajjad/device_xiaomi_lavender -b sa_hmp device/xiaomi/lavender
      - git clone https://github.com/Sa-Sajjad/vendor_xiaomi_lavender -b 10 vendor/xiaomi/lavender
      - git clone https://github.com/Sa-Sajjad/kernel_xiaomi_lavender kernel/xiaomi/lavender
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 50G
      - . build/envsetup.sh
      - lunch nad_lavender-userdebug
      - mka nad -j
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/work
      - cd out/target/product/lavender
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo Nusantara*.zip) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
        
