env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/sa"
    rclone_config: "ENCRYPTED[!812e8ae62bc12b7b59678b17e816936854238a34ed702f4623275c16e483bda637ebb78df877cb34e65bbf04e76b3ae6!]"
task:
    name: test
    timeout_in: 120m
    container:
      image: apon77/aosp:cirrus
      cpu: 8
      memory: 32G
      volumes:
        - /home/cirrus/roms:/home/cirrus/roms
        - /home/cirrus/ccache:/home/cirrus/ccache
        - /home/cirrus/.config:/home/cirrus/.config

    download_script:
      - bash download_ccache

    upload_ccache_script:
      - bash upload_ccache

    sync_script:
      - mkdir -p /tmp/sa
      - cd /tmp/sa
      - repo init --depth=1 --no-repo-verify -u https://github.com/Sa-Sajjad/android_manifest_nusa.git -b 10 -g default,-mips,-darwin,-notdefault
      - git clone https://github.com/Sa-Sajjad/manifest.git --depth 1 -b main .repo/local_manifests
      - repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8


