env:
    CIRRUS_CLONE_DEPTH: 1
    CIRRUS_WORKING_DIR: "/tmp/ci"
    rclone_config: "ENCRYPTED[!812e8ae62bc12b7b59678b17e816936854238a34ed702f4623275c16e483bda637ebb78df877cb34e65bbf04e76b3ae6!]"
task:
    name: test
    timeout_in: 120m
    container:
      image: apon77/aosp:latest
      cpu: 8
      memory: 32G
      volumes:
        - /home/cirrus/roms:/home/cirrus/roms
        - /home/cirrus/ccache:/home/cirrus/ccache
        - /home/cirrus/.config:/home/cirrus/.config

    download_script:
      - bash download_ccache

    sync_script:
      - bash sync

    monitor_background_script:
      - bash monitor

    upload_ccache_script:
      - bash upload_ccache
