env:
    CIRRUS_CLONE_DEPTH: 1
    rclone_config: "ENCRYPTED[!812e8ae62bc12b7b59678b17e816936854238a34ed702f4623275c16e483bda637ebb78df877cb34e65bbf04e76b3ae6!]"
task:
    name: test
    timeout_in: 120m
    container:
      image: apon77/aosp:cirrus
      cpu: 2
      memory: 4G
    show_script:
    - cirrus worker run --token 2imtl41mjof0479pfrlgttcjn66914rjklul0s61bpu2j4hqec4ccgur0puu3alkbpoo7mm0k36so027262dsmh6kquah2qf9bfl20i
